# Generated by Django 5.2.3 on 2025-06-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("telegram_id", models.CharField(max_length=100)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
